service: feredatated-graphql

provider:
  stage: ${self:custom.stageOverride}
  name: aws
  region: ${env:DEPLOYMENT_REGION}
  runtime: nodejs14.x
  memorySize: 512 # Overwrite the default memory size. Default is 1024
  timeout: 15 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  gateway:
    handler: src/gateway/index.graphqlHandler
    events:
      - http:
          path: api
          method: post
          cors: true
      - http:
          path: api
          method: get
          cors: true
  reviews:
    handler: src/subgraph/index.graphqlHandler
    events:
      - http:
          path: reviews
          method: post
          cors: true
      - http:
          path: reviews
          method: get
          cors: true

  comments:
    handler: src/subgraph-2/index.graphqlHandler
    events:
      - http:
          path: comments
          method: post
          cors: true
      - http:
          path: comments
          method: get
          cors: true
